### ISSUE TITLE
Exceptions in event handlers exit silently

### ISSUE THREAD

**Issue by Streetwalrus** [altdesktop/i3ipc-python#125]
Minimal working example:
```python
import i3ipc

def on_window(self, e):
    raise Exception

conn = i3ipc.Connection()
conn.on('window', on_window)
conn.main()
```
This will just exit silently without printing a backtrace, and return code 0. Seems to happen on both 1.7.1 and 2.0.1.

**Comment by acrisci** [comment]
Yeah this isn't good. The `i3ipc.aio.Connection` will raise the exception from the main loop. I should probably just have that behavior for the normal Connection as well.

**Comment by Streetwalrus** [comment]
Thanks!
