### ISSUE TITLE
Regression: Reply-objects don't support indexing anymore

### ISSUE THREAD

**Issue by s-ol** [altdesktop/i3ipc-python#136]
This used to work:

`print(i3ipc.Connection().get_workspaces()[0]['name'])`

if I read [this diff correctly](https://github.com/altdesktop/i3ipc-python/commit/cec29f9a346d5295a7ad21a057bfd27e7e108413#diff-830fc5c84c34393be66221bdfa8affad), then both `workspace.name` and `workspace['name']` used to work.

Should the ability to index via subscription be reimplemented? A simple addition like

```py
class _BaseReply
    # ...
    def __getitem__(self, k):
        return getattr(self, k)

    def __setitem__(self, k, v):
        return setattr(self, k, v)

    def __delitem__(self, k):
        return delattr(self, k)
```

should suffice.

**Comment by acrisci** [comment]
Yeah this was a breaking change in 2.0. Why would you want both?

**Comment by s-ol** [comment]
For compatibility, it seems kind of unecessary to break this. This also isn't mentioned in the 2.0.1 release notes.

**Comment by acrisci** [comment]
You can put it back in like that if you want, but don't document it and mark it as deprecated.

**Comment by s-ol** [comment]
Okay... but if that means you will remove the feature again in a later update I will rather patch downstream.
