### ISSUE TITLE
Packaging notice

### ISSUE THREAD

**Issue by kgilmer** [altdesktop/i3ipc-python#139]
Hi! I have packaged i3ipc-python as a Debian package for Regolith.  I have not tested it yet other than inspecting which files made it into the deb file.  I patched the Makefile to remove the test execution, linter, and and docker tests.

This issue is just a courtesy message to let you know of the package.

Package metadata is here: https://github.com/regolith-linux/speed-ricer/tree/master/i3ipc-python/debian

PPA hosting the package is here: https://launchpad.net/~kgilmer/+archive/ubuntu/speed-ricer

**Comment by acrisci** [comment]
Cool, thanks for packaging it :+1: . Let me know if there's anything I can do to help.
