### ISSUE TITLE
Problem with workspace focus when the name starts with space

### ISSUE THREAD

**Issue by ashish-yadav11** [altdesktop/i3ipc-python#146]
I have my workspace names in i3 set to start with space (for example " 1: ").
`workspace_name = " 1: \uf015"`
`i3.command(f'workspace {workspace_name}')`
The above code in python3, with i3 as the connection object, takes me to workspace "1: " instead of " 1: ".

**Comment by acrisci** [comment]
Try quoting your workspace name.

```
i3.command(f'workspace "{workspace_name}"')
```

**Comment by ashish-yadav11** [comment]
It worked. Thanks
