### ISSUE TITLE
High number of calls to sway socket

### ISSUE THREAD

**Issue by ammgws** [altdesktop/i3ipc-python#147]
I have been using this [autotiling](https://github.com/nwg-piotr/autotiling/blob/master/autotiling.py) script which uses i3ipc, and lately found the python3 process pegging my CPU.

After running strace on the process for about 30 seconds I found over 16 million calls to the sway socket:
![image](https://user-images.githubusercontent.com/20397027/74684808-28760900-5210-11ea-8827-58125fe86784.png)

Socket looks to be at least responding to these calls, but with a 0 length response:
![image](https://user-images.githubusercontent.com/20397027/74684999-99b5bc00-5210-11ea-9fe6-f64bcc31a834.png)

NOTE: I have been trying to pinpoint an issue with my sway install where the ipc server seemingly appears to die, so the socket not returning anything is probably related to that, however the number of calls seems like something i3ipc has control over. Posting here in case there is an failure mode that hasn't yet been addressed in the code.

**Comment by acrisci** [comment]
I can look into this, although further debugging would be appreciated. I wonder if there is an infinite loop in the script where the command causes the event you are listening to.

**Comment by ammgws** [comment]
Might be that something doesn't like the fact that the IPC response is 0 and keeps spamming for updates? 

Next time it happens I'll try debugging the _ipc_recv/_event_socket_poll functions. From a quick skim of the code if the socket returns no data then i3ipc-python emits "ipc-shutdown", and it might be the start of the loop.

**Comment by ammgws** [comment]
Came home to find a different failure mode, not sure if it is related. This time strace output looks normal apart from the EPIPEs. Seems like the `autotiling.py`/`i3ipc-python` side has closed the socket or something.

[![asciicast](https://asciinema.org/a/YYJjzy1G5Xg0xoN6u0N2WDBmM.svg)](https://asciinema.org/a/YYJjzy1G5Xg0xoN6u0N2WDBmM)

Will try investigate some more later.

**Comment by ammgws** [comment]
Don't think I've encountered this in a while (either due to using a different autotiling script or the problem just having gone away after changes in sway/etc), so I will close the isue.
