### ISSUE TITLE
Random test failures

### ISSUE THREAD

**Issue by alebastr** [altdesktop/i3ipc-python#149]
I'm trying to update the package for Fedora and one of the blockers is intermittent test failures.

The failure reasons are varied: sometimes it's timeout in `test/aio/test_workspace.py`, other times it's honest error in `test_windows` or `test_get_marks` (which I'm attributing to timing issues).

Logs: https://gist.github.com/alebastr/37d56db5351b458d522f4f15092b3a1c

**Comment by acrisci** [comment]
I think I can fix those by implementing the sync protocol. I should be paying some more attention to the project pretty soon.

**Comment by acrisci** [comment]
I'm pretty sure this is fixed now.
