### ISSUE TITLE
Sway: input command

### ISSUE THREAD

**Issue by hissssst** [altdesktop/i3ipc-python#154]
### Problem
executing `conn.command("input \* xkb_switch_layout 1")` doesn't work, but `os.system("swaymsg inpurt \* xkb_switch_layout 1")` does

### Actual behaviour
`conn.command("input \* xkb_switch_layout 1")` does not change the keyboard layout

### Desired behaviour
`conn.command("input \* xkb_switch_layout 1")` changes the keyboard layout

### Versions
```
sway version 1.4
python-i3ipc 2.2.1
wlroots 0.10.1
```

**Comment by acrisci** [comment]
What is the result of the command? You might have an error message there.

```
result = conn.command(...)
print(result)
```

**Comment by hissssst** [comment]
@acrisci 
```
>>> conn.command("input \* xkb_switch_layout 1")[0].__dict__
{'ipc_data': {'success': True}, 'success': True, 'error': None}
```

**Comment by acrisci** [comment]
I bet it's that forward slash. In the shell it escapes the star but `command()` I believe sends literal forward slash, which is probably a valid way to match an input. So try removing it.

```
conn.command("input * xkb_switch_layout 1")
```

**Comment by hissssst** [comment]
@acrisci
That works, thank you!

P.S. I am really sorry for opening this dumb issue :\
