### ISSUE TITLE
get Pid in i3

### ISSUE THREAD

**Issue by windwp** [altdesktop/i3ipc-python#156]
Is there anyway to get pid in i3 not sway?

**Comment by acrisci** [comment]
Not with the ipc. But you can try to read `_NET_WM_PID` property of the window with an X11 library. Check out the `xprop` command.

**Comment by windwp** [comment]
Yeah i know that xprop command.

**Comment by acrisci** [comment]
Check out the [python-xlib](https://github.com/python-xlib/python-xlib) library.
