### ISSUE TITLE
Bad json from self._message(MessageType.GET_TREE, '')

### ISSUE THREAD

**Issue by MatrixManAtYrService** [altdesktop/i3ipc-python#160]
Hi, thanks for making this library, it's very helpful.

I'm not sure what changed.  One minute everything was working smoothly and the next minute calls to `get_tree()` started failing.

I added a print statement to see what was going on:
```
~/src/myproject/venv/lib/python3.8/site-packages/i3ipc/connection.py in get_tree(self)
    282         data = self._message(MessageType.GET_TREE, '')
    283         print(data) # <--- I added this line
--> 284         return Con(json.loads(data), None, self)
    285 
    286     def get_marks(self) -> List[str]:
```

And found that the contents of `data` included a region where the commas had gone missing:

```
...current_border_width":-1,"rect":{"x":2104,"y":1440,"width":1536,"height":1410},"deco_rect":{"x":0,"y":0,"width":0,"height":0},"window_rect":{"x":0,"y":0,"width":0,"height":0},"geometry":{"x":0,"y":0,"width":0,"height":0},"name":null,"window":null,"window_type":null,"nodes":[{"id":94437733399072,"type":"con","orientation":"none","scratchpad_state":"none","percent":1.0,"urgent":false,"focused":true,"output":"DP-2","layout":"splith","workspace_layout":"default","last_split_layout":"splith","border":"normal","current_border_width":2,"rect":"x"2104"y"1468"width"1536"height"1382}...
```
(it starts with the second instance of `current_border_width`)

I'm not sure where that data comes from, so I'm sorry if this bug report is in the wrong place, but I wanted to at least put it somewhere.

----

 ❯ i3 --version
i3 version 4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors

**Comment by acrisci** [comment]
It looks like an i3 bug. If you can reproduce it with `i3-msg -t get_tree` you can post it on their tracker.

**Comment by MatrixManAtYrService** [comment]
Thanks for that command.  I've since rebooted, so it's gone, but if it comes back I'll be sure to post it in the right place.

**Comment by MatrixManAtYrService** [comment]
https://github.com/i3/i3/issues/4167
