### ISSUE TITLE
Exception: Failed to retrieve the i3 or sway IPC socket path (running default example)

### ISSUE THREAD

**Issue by santiagodemierre** [altdesktop/i3ipc-python#161]
Exception                                 Traceback (most recent call last)
<ipython-input-1-5bef458d320a> in <module>
      3 # Create the Connection object that can be used to send commands and subscribe
      4 # to events.
----> 5 i3 = Connection()
      6 
      7 # Print the name of the focused window

~/.local/lib/python3.6/site-packages/i3ipc/connection.py in __init__(self, socket_path, auto_reconnect)
     66 
     67         if not socket_path:
---> 68             raise Exception('Failed to retrieve the i3 or sway IPC socket path')
     69 
     70         if auto_reconnect:

Exception: Failed to retrieve the i3 or sway IPC socket path

**Comment by santiagodemierre** [comment]
This solves it:
connection.py

if not socket_path:
            socket_path = str(subprocess.check_output("i3 --get-socketpath",shell=True).decode().strip())

**Comment by acrisci** [comment]
Unfortunately I eat the error that would tell you why that failed. I need to add better logging.

**Comment by acrisci** [comment]
I also need to add the logic to get it from the binary if the other methods fail.

**Comment by acrisci** [comment]
I've added logging and the alternative socket path finding mechanism. This should be fixed.
