### ISSUE TITLE
Documentation con floating (bool) should be floating (string)

### ISSUE THREAD

**Issue by select** [altdesktop/i3ipc-python#164]
https://i3ipc-python.readthedocs.io/en/latest/con.html
While the documentation claims that floating is a boolean value for me it returns the strings 
- auto_off
- user_on
where user_on is for floating windows.

Not sure this is due to my i3 version, I just wanted to let you know of this small missmatch that I discovered. 

Other that, thanks for the great library, I started writing an auto layouter with it.

**Comment by acrisci** [comment]
It's not documented, but according to the source, the possible values are "auto_off", "auto_on", "user_off", "user_on".

**Comment by acrisci** [comment]
Also added `Con.is_floating()` to get this as a boolean value.
