### ISSUE TITLE
stop application on unfocus -- copy/paste issue

### ISSUE THREAD

**Issue by pizdjuk** [altdesktop/i3ipc-python#169]
If copying something from browser window, which is supposed to be stopped on lose of focus, nothing can be pasted in other window till browser window will be activated other time.

Workaround -- set a timeout to lose of the focus, 10 or 15 seconds would be enough.

**Comment by acrisci** [comment]
There's nothing I can do about this. Copy/paste requires the process that owns the clipboard to be running to send the contents.

**Comment by pizdjuk** [comment]
One can wait some timeout before suspend the process.

**Comment by pizdjuk** [comment]
The bug is out of scope of this plugin. So, closing the bug.
