### ISSUE TITLE
`Con` classes are missing the `shell` attribute as mentioned in the sway ipc spec

### ISSUE THREAD

**Issue by rifazn** [altdesktop/i3ipc-python#172]
The `Con` class is missing a sway-only attribute, `shell`, which is included in the sway-ipc specification.

Should this be included for compatibility with sway?

There are other sway-only attributes included within the library (`app_id`, `pid`, `representation` and `visible`) so this attribute is probably missing here.

Sway-ipc spec: https://man.archlinux.org/man/sway-ipc.7.en#4._GET_TREE

**Comment by acrisci** [comment]
Yeah go ahead and do a PR for it.

**Comment by rifazn** [comment]
PR: #173
