### ISSUE TITLE
Missing sway visible attribute

### ISSUE THREAD

**Issue by g33kex** [altdesktop/i3ipc-python#177]
In sway's tree there is a "visible" attribute that tells whether a node is visible or not : https://man.archlinux.org/man/sway-ipc.7.en#4._GET_TREE

The "visible" attribute is present in i3ipc documentation, but is not implemented:
https://github.com/altdesktop/i3ipc-python/blob/14b56362cbdd44dcb3c798e246e01198b94cf4d3/i3ipc/con.py#L94-L98

**Comment by acrisci** [comment]
You can go ahead and add that if you want.
