### ISSUE TITLE
focus-last.py cycles only last two windows

### ISSUE THREAD

**Issue by Werkov** [altdesktop/i3ipc-python#50]
There's `MAX_WIN_HISTORY` in the script, however, AFAICT it's to handle deleted/closed windows.

I've an idea how to implement this with some timeout reading the communication socket, so that multiple invocations could be used to cycle stack-like through windows.

(I'm filing an issue, in case someone else had more time than me :-)

**Comment by acrisci** [comment]
@nicoe is the author of that script.

**Comment by nicoe** [comment]
`MAX_WIN_HISTORY` is there in order to prevent the window list to grow indefinitely and only for that.
Of course I don't see any problem with the change your suggesting (I just happen to rarely having to go farther then the previous window).

**Comment by eugenevd** [comment]
@Werkov
I understand focus-last to be exactly that, switch to the previously focussed window.

Wouldn't https://github.com/altdesktop/i3ipc-python/blob/master/examples/i3-cycle-focus.py be closer to what you're after?

**Comment by Werkov** [comment]
Thanks for notifyin me about this, it is closer to my use case indeed. (I just need to adjust the delay properly and `s/container\.props\./container\./` to work with my version of i3. Since issue is covered with i3-cycle-focus.py, I'm closing this issue.
