### ISSUE TITLE
Sway compatibility

### ISSUE THREAD

**Issue by trobjo** [altdesktop/i3ipc-python#98]
Hi

This looks very promising, as I've been looking for at way to temporarily freeze unfocused clients.

You mention in the lead paragraph that this is a python library to control i3 and Sway. I am quite new to this whole IPC thing (but willing to learn), but I can't seem to find any further documentation on how to convert the i3 scripts to become sway compatible. Is it just me that need to go learn some more Python, or what am I missing here?

**Comment by acrisci** [comment]
What's not working?

**Comment by trobjo** [comment]
I played around with it further, and the workspace-new.py example works fine so your library is probably 1:1 compatible with sway.

Now I don't speak python, so I can't say for sure, but there were a lot of examples I just couldn't get to work. I suppose it's because they involve class_name, since Wayland apps use app_id instead of class. 

I was probably too quick to file a bug report, since this seems to be an issue with the concrete implementations and not your library per se. Sorry about that.

**Comment by trobjo** [comment]
The tree layout in Sway is different. Compare https://i3wm.org/docs/ipc.html with https://transfer.sh/FXtjj/tree.json

There is no  "window_properties" in Sway. As far as I can see, everything is contained within "nodes"{} in Sway. 

That would certainly explain why I could only get the "workspace-new.py" to work.

**Comment by fennerm** [comment]
@acrisci Any chance https://github.com/acrisci/i3ipc-python/commit/8d3f5d846943f8728b14ac0537c92898d53b35db will be included into a release soon?

**Comment by acrisci** [comment]
It's kind of a complicated release because I'm adding asyncio and dropping python2 but I should get it out soon. In the meantime, test more sway features. It should be completely compatible.

**Comment by fennerm** [comment]
Awesome thanks for the update. I’ve been testing it and its all running great so far :)

**Comment by tmccombs** [comment]
Another compatibility issue is that the "visible" property isn't exposed. More generally, I wonder if there should be some way to access fields that aren't explicitly handled by i3ipc. Either by setting attributes for any properties that i3ipc doesn't know about, or keeping the original data, so it is accessible if needed.

**Comment by tmccombs** [comment]
Also, at least in sway, outputs additional information on them (for example "current_workspace", "current_mode", etc.)

**Comment by acrisci** [comment]
> Another compatibility issue is that the "visible" property isn't exposed.

> Also, at least in sway, outputs additional information on them (for example "current_workspace", "current_mode", etc.)

It's easy to add properties.

> More generally, I wonder if there should be some way to access fields that aren't explicitly handled by i3ipc.

Yeah it would probably be a good idea to store the "raw_properties" in a dict for access of anything I'm missing.

**Comment by maximbaz** [comment]
It also seems that scratchpad is not supported on sway, `Connection().get_tree().scratchpad()` returns `None`.

**Comment by acrisci** [comment]
They probably put the scratchpad container in a different place in the tree.

**Comment by tmccombs** [comment]
The scratchpad is definitely in the tree output, so it probably is just in a different place.

**Comment by acrisci** [comment]
I just added an `ipc_data` member to the types that gives you the raw json for forwards compatibility with sway members.

**Comment by acrisci** [comment]
I added all the properties that are known to me at this time. The only thing left is to fix the scratchpad.

**Comment by acrisci** [comment]
I believe I'm completely sway compatible right now. Thanks for the input and open separate issues for anything else. I'll release in a few days, so go ahead and test.
